### ISSUE TITLE
enigmaze關卡404

### ISSUE THREAD

**Issue by r888800009** [LianSheng197/liansheng197.github.io#1]
這邊因為在連結的時候會變成絕對路徑而非相對路徑，因此會出現404。

https://github.com/LianSheng197/liansheng197.github.io/blob/2daf04e656392a8ab4ecdcc45800610dce9820c7/enigmaze/js/intro.js#L20
https://github.com/LianSheng197/liansheng197.github.io/blob/2daf04e656392a8ab4ecdcc45800610dce9820c7/enigmaze/js/intro.js#L25

**Comment by LianSheng197** [comment]
啊，這個我知道，原因是起先是直接放在 localhost 設計的，丟到 GitHub 上後沒有特別更改它的網站根目錄應由 /enigmaze 開始而導致。

嘛，那是個暫停很久不知道什麼時候會再繼續的沒營養的小專案，主要是缺乏創意變不出東西，而且原始碼寫得很沒有水準，下次有機會重啓估計又會打掉重練XDD
